namespace ATA.Domain.Common;

public static class ErrorCodes
{
    public const string ValidationFailed = "validation_failed";
    public const string Unauthorized = "unauthorized";
    public const string InvalidCredentials = "invalid_credentials";
    public const string Forbidden = "forbidden";
    public const string NotFound = "not_found";
    public const string Conflict = "conflict";
    public const string RateLimited = "rate_limited";
    public const string OtpInvalid = "otp_invalid";
    public const string OtpExpired = "otp_expired";
    public const string OtpLocked = "otp_locked";
    public const string PhoneInvalid = "phone_invalid";
    public const string AccountSuspended = "account_suspended";
    public const string DriverNotApproved = "driver_not_approved";
    public const string FileTooLarge = "file_too_large";
    public const string UnsupportedFileType = "unsupported_file_type";
    public const string InsufficientBalance = "insufficient_balance";
    public const string TripActiveExists = "trip_active_exists";
    public const string OfferExpired = "offer_expired";
    public const string PinInvalid = "pin_invalid";
    public const string PinLocked = "pin_locked";
    public const string OfferOutOfRange = "offer_out_of_range";
    public const string QuoteExpired = "quote_expired";
    public const string PaymentFailed = "payment_failed";
    public const string PaymentMethodExpired = "payment_method_expired";
    public const string PaymentMethodInUse = "payment_method_in_use";
    public const string PaymentProviderUnavailable = "payment_provider_unavailable";
    public const string WebhookSignatureInvalid = "webhook_signature_invalid";
    public const string RefundExceedsAmount = "refund_exceeds_amount";
    public const string FourEyesRequired = "four_eyes_required";
    public const string PayoutBelowMinimum = "payout_below_minimum";
    public const string PayoutPendingExists = "payout_pending_exists";
    public const string IbanMissing = "iban_missing";
    public const string CashDebtLimitExceeded = "cash_debt_limit_exceeded";
    public const string OutstandingBalance = "outstanding_balance";
    public const string SettlementPeriodOverlap = "settlement_period_overlap";
    public const string UnknownEventCode = "unknown_event_code";
    public const string CampaignNotEditable = "campaign_not_editable";
    public const string TemplatePlaceholderInvalid = "template_placeholder_invalid";
    public const string ShareNotFound = "share_not_found";
    public const string ShareExpired = "share_expired";
    public const string TrustedContactsLimit = "trusted_contacts_limit";
    public const string TrustedContactExists = "trusted_contact_exists";
    public const string ChatClosed = "chat_closed";
    public const string LostItemWindowClosed = "lost_item_window_closed";
    public const string CancellationReasonInvalid = "cancellation_reason_invalid";
    public const string CancellationFeeChanged = "cancellation_fee_changed";
    public const string NoShowTooEarly = "no_show_too_early";
    public const string AccountRestricted = "account_restricted";
    public const string InternalError = "internal_error";
}
