import 'package:ata_app/core/usecases/use_case.dart';
import 'package:ata_app/core/utils/money.dart';
import 'package:ata_app/features/driver_wallet/domain/entities/payout_summary.dart';
import 'package:ata_app/features/driver_wallet/domain/usecases/get_payout_summary.dart';
import 'package:ata_app/features/driver_wallet/domain/usecases/request_payout.dart';
import 'package:ata_app/features/driver_wallet/presentation/cubit/payout_request_state.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

/// Loads the payout limits, validates the amount and submits the request
/// (`Idempotency-Key` generated by the repository).
class PayoutRequestCubit extends Cubit<PayoutRequestState> {
  PayoutRequestCubit({required this._getSummary, required this._request})
    : super(const PayoutRequestState());

  final GetPayoutSummary _getSummary;
  final RequestPayout _request;

  Future<void> load() async {
    emit(state.copyWith(loading: true, clearFailure: true));
    final result = await _getSummary(const NoParams());
    emit(
      result.fold(
        (failure) => state.copyWith(loading: false, failure: failure),
        (PayoutSummary summary) => state.copyWith(
          loading: false,
          summary: summary,
          amountText: state.amountText.isEmpty && summary.canRequest
              ? Money.integer(summary.availableForPayout)
              : null,
        ),
      ),
    );
  }

  void amountChanged(String text) {
    if (state.submitting) return;
    emit(state.copyWith(amountText: text, clearFailure: true));
  }

  Future<void> submit() async {
    final PayoutSummary? summary = state.summary;
    final double? amount = state.amount;
    if (!state.canSubmit || summary == null || amount == null) return;
    emit(state.copyWith(submitting: true, clearFailure: true));
    final result = await _request(
      PayoutRequestParams(
        amount: amount,
        minAmount: summary.minPayoutAmount,
        available: summary.availableForPayout,
      ),
    );
    emit(
      result.fold(
        (failure) => state.copyWith(submitting: false, failure: failure),
        (payout) => state.copyWith(submitting: false, payout: payout),
      ),
    );
  }
}
