name: ata_app
description: "ATA ride-hailing app (rider + driver) - Step 1."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  fpdart: ^1.1.1
  get_it: ^8.0.3
  go_router: ^14.8.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  signalr_netcore: ^1.4.4
  geolocator: ^14.0.2
  share_plus: ^12.0.2
  onesignal_flutter: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo.png

  fonts:
    - family: IBM Plex Sans Arabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
